sudo: required
services:
  - docker

before_install:
  - docker build -t jdcarroll22/test-kube -f ./client/Dockerfile.dev ./client

script:
  - docker run jdcarroll22/test-kube npm test -- --coverage

after_success:
  - docker build -t jdcarroll22/test-kube-client ./client
  - docker build -t jdcarroll22/test-kube-nginx ./nginx
  - docker build -t jdcarroll22/test-kube-server ./server
  - docker build -t jdcarroll22/test-kube-worker ./worker
  # Docker Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images up to docker hub
  - docker push jdcarroll22/test-kube:jdcarroll22/test-kube-client
  - docker push jdcarroll22/test-kube:jdcarroll22/test-kube-nginx
  - docker push jdcarroll22/test-kube:jdcarroll22/test-kube-nginx
  - docker push jdcarroll22/test-kube:jdcarroll22/test-kube-nginx
